---
# yaml variables for profile
global:
  main_bucket_name: devopsblog-remote-states-tf
  ssh_key: test_terr

ansible:
  instance_type: t2.micro
  image_id: ami-09447c6f

bastion:
  instance_type: t2.micro
  image_id: ami-09447c6f

nat:
  instance_type: t2.micro
  image_id: ami-09447c6f
